version: "3.4"

volumes:
  rabbitmq:
  mongodata:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: "baslake-timescaledb"
    restart: always
    networks: 
      - baslake
    ports: 
      - 5432:5432
    env_file: 
      - .env

  adminer:
    image: adminer:latest
    container_name: "baslake-timescale-adminer"
    restart: always
    networks: 
      - baslake
    ports:
      - 8080:8080
  
  logs:
    image: amir20/dozzle:latest
    container_name: baslake-log
    networks:
      - baslake
    ports:
    - 8888:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
    baslake:
        external: true
